### ISSUE TITLE
Database Missing ?

### ISSUE THREAD

**Issue by T-Tron** [TheThief/SpaceMMO#1]
Hello !
I would like to know, do you have a database ?

**Comment by CiroboyBR** [comment]
Yes, db_account.inc.php not found and. No SQL for create tables...

**Comment by markbeazley** [comment]
Yeah no DB dump currently available, but you should be able to recreate the DB and the database credentials file db_account.inc.php

Inside the admin folder are a bunch of files in the form create*table.php you should be able to find the queries needed to build the DB there.

db_account.inc.php was just a file that defined the DB credentials, should just be something along the lines of this
```php
<?php
$db_server = 'hostname';
$db_admin_user = 'adminuser';
$db_admin_pass = 'adminpassword';
$db_user = 'user';
$db_pass = 'password';
$db_db = 'databsename';
```
You'll need to fill those in with the values for your database, I believe the only difference between the admin and user credentials was the admin user had the ability to alter schema, and the user credentials were only allowed to query and alter the data.

**Comment by markbeazley** [comment]
Other things to note that may not be documented:

1. [tick.php](https://github.com/TheThief/SpaceMMO/blob/main/admin/private/tick.php) needs to run as a cron task once a minute to update the game
2. [generate_universe_exec.php](https://github.com/TheThief/SpaceMMO/blob/main/admin/generate_universe_exec.php) is used to seed the universe, how ever the current version was a trial for a new seeding system that used an image mask, [this](https://github.com/TheThief/SpaceMMO/blob/9b209ef0fdc00829aee7f9f86315788e2aad9c07/admin/generate_universe_exec.php) version with the commented lines in the foreach loops uncommented and some fixes to work with PHP 7.1 should generate the galaxy correctly

**Comment by T-Tron** [comment]
Oh thanks !

**Comment by TheThief** [comment]
I have added the database, minus any user accounts or active game content (colonies, fleets, etc), and instructions to deploy in the releases: https://github.com/TheThief/SpaceMMO/releases/tag/v1.0-Sunset2020

Good luck to anyone that wants to try this mess
